apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-app
spec:
  selector:
    matchLabels:
      app: astro-app
  template:
    metadata:
      labels:
        app: astro-app
    spec:
      containers:
      - name: astro-app
        image: eu.gcr.io/astro-app-332210/astro-app:latest        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
