# Default values for astro-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

astroappdp:
  name: astro-app
  namespace: astro-app
  containers:
    image: eu.gcr.io/astro-app-332210/astro-app:latest
    containerPort: 5000

astroappsvc:
  name: astro-app
  spec:
    ports:
      port: 80
      targetPort: 5000
    type: ClusterIP

mongosvc:
  name: mongo-svc
  spec:
    ports:
      port: 27017
      targetPort: 27017
    type: ClusterIP
  
mongodp:
  name: mongo
  namespace: astro-app
  image: bitnami/mongodb:3
  ports:
    containerPort: 27017

mongosecret:
  name: mongo-secret
  password: cGFzc3dvcmQ=
  db: ZGI=

mongopvc:
  name: mongo-pvc
  request:
    storage: 1Gi

nginxdp:
  name: nginx
  image: nginx:stable-alpine
  ports:
    containerPort: 80

nginxsvc:
  name: nginx-svc
  port: 80 
  type: LoadBalancer

ingress:
  enabled: true
  name: ingress-nginx
  hosts:
    host: joaffzie.tk
    paths:
      path: /
      pathType: ImplementationSpecific
  service: 
    name: nginx-svc
    port: 80

