apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongosecret.name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  password: {{ .Values.mongosecret.password }}
  db: {{ .Values.mongosecret.db }}