apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongosvc.name }}
  namespace: astro-app
spec:
  selector:
    app: {{ .Values.mongodp.name }}
  ports:
  - port: {{ .Values.mongosvc.spec.ports.port }}
    targetPort: {{ .Values.mongosvc.spec.ports.targetPort }}
  type: {{ .Values.mongosvc.spec.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodp.name }}
  namespace: {{ .Values.mongodp.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongodp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodp.name }}
    spec:
      containers:
      - name: {{ .Values.mongodp.name }}
        image: {{ .Values.mongodp.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.mongodp.ports.containerPort }}
        # volumeMounts:
        #   - mountPath: /bitnami/mongodb
        #     name: mongo-pvc
        env:
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: db
      # volumes:
      #   - name: mongo-pvc
      #     persistentVolumeClaim:
      #       claimName: mongo-pvc
