apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongopvc.name }}
  namespace: astro-app
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  resources:
    requests:
      storage: {{ .Values.mongopvc.request.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
