apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginxsvc.name }}
  namespace: astro-app
spec:
  selector:
    app: {{ .Values.nginxdp.name }}  
  ports:
  - port: {{ .Values.nginxsvc.port }}  
    targetPort: {{ .Values.nginxdp.ports.containerPort }}   
  type: {{ .Values.nginxsvc.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginxdp.name }}  
  namespace: astro-app
spec:
  selector:
    matchLabels:
      app: {{ .Values.nginxdp.name }}  
  template:
    metadata:
      labels:
        app: {{ .Values.nginxdp.name }}  
    spec:
      containers:
      - name: {{ .Values.nginxdp.name }}  
        image: {{ .Values.nginxdp.image }}  
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.nginxdp.ports.containerPort }}  
        volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-conf 
          - mountPath: /usr/share/nginx/html/
            name: nginx-static
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-static
          configMap:
            name: nginx-static
